type: fields

fields:
  settings_site_headline:
    type: headline
    numbered: true
    label:
      en: Website Information
      de: Website Information

  settings_site: fields/settings/site

  settings_privacy_headline:
    type: headline
    numbered: true
    label:
      en: Privacy
      de: Privatsph√§re

  settings_privacy: fields/settings/privacy
